#!/usr/bin/env node
/**
 * Assemble a DWC 3.6-shaped plugin source tree in a temp directory.
 *
 * DWC's `build-plugin-pkg` (both generations) copies a fixed `<pluginDir>/src` and builds
 * `src/index.ts`. It cannot be pointed at `src/ui36/`, and it would happily try to compile
 * `src/ui37/` too - which fails immediately, since Vuetify 4 / Pinia / `@/plugins` do not exist in a
 * 3.6 checkout. So rather than fight it, stage a tree that contains only what the 3.6 build needs.
 *
 * The staged tree keeps the repo's directory shape exactly (`ui36/` stays a subdirectory), so every
 * relative import inside the shared and 3.6 sources resolves unchanged. The only new file is a
 * one-line `src/index.ts` pointing at the 3.6 entry, mirroring what the repo's own `src/index.ts`
 * does for 3.7.
 *
 *   node scripts/stage-dwc36.mjs [outDir]
 *
 * Prints the staged directory as its last line, for the caller to pass to build-plugin-pkg.
 */
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repo = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = resolve(process.argv[2] ?? join(tmpdir(), "resonance-lab-dwc36"));

/** Shared, version-neutral sources plus the 3.6 UI. `ui37/` is deliberately absent. */
const INCLUDE = ["analysis", "capture", "config", "core", "i18n", "ui36", "state.ts", "updateCheck.ts"];

/**
 * Bundled dependencies that must NOT come from the DWC checkout.
 *
 * DWC 3.7 happens to ship chart.js 4, which is why the 3.7 build just works; DWC 3.6 ships chart.js
 * 2.9, whose API this plugin's charts predate by two majors (`chart.js/auto` does not even exist
 * there). Installing v4 into the 3.6 checkout would break DWC's own charts, so instead the plugin's
 * copy is staged into a `node_modules` INSIDE the plugin's source folder: webpack resolves package
 * imports by walking up from the importing file, so `src/plugins/ResonanceLab/node_modules/chart.js`
 * is found before the checkout's own. Same trick for dwc-plugin-runtime, which 3.6 has never heard
 * of - which keeps this build reproducible on any 3.6 checkout with no manual preparation.
 */
const VENDOR = ["chart.js", "dwc-plugin-runtime"];

rmSync(outDir, { recursive: true, force: true });
mkdirSync(join(outDir, "src"), { recursive: true });

for (const entry of INCLUDE) {
	cpSync(join(repo, "src", entry), join(outDir, "src", entry), { recursive: true });
}

/** Copy a package and, recursively, everything it depends on (npm's flat layout makes this a simple
 *  walk of the repo's own node_modules). Without the closure webpack stops at the first transitive
 *  import it cannot resolve - e.g. chart.js needs @kurkle/color. */
function vendor(name, seen = new Set()) {
	if (seen.has(name)) {
		return;
	}
	seen.add(name);
	const from = join(repo, "node_modules", name);
	if (!existsSync(from)) {
		throw new Error(`Cannot vendor ${name}: not installed. Run npm install first.`);
	}
	cpSync(from, join(outDir, "src", "node_modules", name), { recursive: true });
	let deps = {};
	try {
		deps = JSON.parse(readFileSync(join(from, "package.json"), "utf8")).dependencies ?? {};
	} catch {
		// no manifest / unreadable — nothing further to pull in
	}
	for (const dep of Object.keys(deps)) {
		vendor(dep, seen);
	}
}

const vendored = new Set();
for (const dep of VENDOR) {
	vendor(dep, vendored);
}

writeFileSync(
	join(outDir, "src", "index.ts"),
	`/**
 * Generated by scripts/stage-dwc36.mjs - do not edit.
 *
 * DWC's plugin builder always compiles src/index.ts; for the DWC 3.6 package that has to be the
 * Vue 2.7 / Vuetify 2 entry point rather than the repo's default 3.7 one.
 */
export * from "./ui36/index";
`,
);

// The manifest travels with the source. `dwcVersion: "auto-major"` is resolved by build-plugin-pkg
// against whichever DWC is doing the building, so the same file yields a 3.6-tagged package here
// and a 3.7-tagged one from build.bat - no separate manifest to keep in sync.
const manifest = JSON.parse(readFileSync(join(repo, "plugin.json"), "utf8"));
writeFileSync(join(outDir, "plugin.json"), `${JSON.stringify(manifest, null, "\t")}\n`);

console.log(`Staged DWC 3.6 sources (v${manifest.version}), vendoring: ${[...vendored].join(", ")}`);
console.log(outDir);
