name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    uses: jaysuk/dwc-plugin-test-kit/.github/workflows/dwc-plugin-ci.yml@v0.2.2
    with:
      dwc-ref: v3.7-dev
      kit-ref: v0.2.2
